# Generated by Django 5.0.6 on 2026-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Node name')),
                ('host', models.CharField(help_text='Public domain name or IP address reachable by VPN clients.', max_length=255, verbose_name='Host or IP address')),
                ('port', models.PositiveIntegerField(default=51820, help_text='Base port used by the VPN service on this node.', verbose_name='VPN port')),
                ('vpn_type', models.CharField(choices=[('wireguard', 'WireGuard'), ('openvpn', 'OpenVPN'), ('ipsec', 'IPsec')], default='wireguard', max_length=20, verbose_name='VPN protocol/type')),
                ('public_certificate', models.TextField(help_text='Public certificate in PEM format or public key (e.g. WireGuard public key).', verbose_name='Public certificate or key')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this VPN node is currently operational.', verbose_name='Active')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VPN Node',
                'verbose_name_plural': 'VPN Nodes',
                'ordering': ['name'],
            },
        ),
    ]
