# Generated by Django 5.0.6 on 2026-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnnode',
            name='internal_ip',
            field=models.CharField(blank=True, default='', help_text='Internal tunnel IP address of the VPN node (e.g. 10.8.0.1 or 10.8.0.1/24).', max_length=50, verbose_name='Internal IP'),
        ),
    ]
