# Generated by Django 5.0.6 on 2026-03-05 02:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ticket code')),
                ('profile_name', models.CharField(help_text='Name of the MikroTik hotspot user profile to assign.', max_length=100, verbose_name='Hotspot profile')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Session duration that will be applied as limit-uptime on the router.', verbose_name='Duration (minutes)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('mk_user_id', models.CharField(blank=True, default='', help_text='RouterOS *.id of the created hotspot user, set on activation.', max_length=50, verbose_name='MikroTik user ID')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activated at')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='routers.router', verbose_name='Router')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
