# Generated by Django 5.0.6 on 2026-03-05 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_id', models.CharField(blank=True, default='', help_text='The *.id returned by the RouterOS API, e.g. *1.', max_length=50, verbose_name='MikroTik ID')),
                ('name', models.CharField(max_length=100, verbose_name='Profile name')),
                ('rate_limit', models.CharField(blank=True, default='', help_text="MikroTik rate-limit string, e.g. '2M/2M'.", max_length=100, verbose_name='Rate limit')),
                ('session_timeout', models.CharField(blank=True, default='', help_text="RouterOS time string, e.g. '1h30m'.", max_length=50, verbose_name='Session timeout')),
                ('shared_users', models.PositiveIntegerField(default=1, verbose_name='Max simultaneous sessions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_profiles', to='routers.router', verbose_name='Router')),
            ],
            options={
                'verbose_name': 'Hotspot Profile',
                'verbose_name_plural': 'Hotspot Profiles',
                'ordering': ['router', 'name'],
                'unique_together': {('router', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HotspotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_id', models.CharField(blank=True, default='', max_length=50, verbose_name='MikroTik ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Disabled on router')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hotspot.hotspotprofile', verbose_name='Profile')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_users', to='routers.router', verbose_name='Router')),
            ],
            options={
                'verbose_name': 'Hotspot User',
                'verbose_name_plural': 'Hotspot Users',
                'ordering': ['router', 'username'],
                'unique_together': {('router', 'username')},
            },
        ),
    ]
