# Generated by Django 5.0.6 on 2026-03-26 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Template name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('vendor', models.CharField(choices=[('mikrotik', 'MikroTik')], default='mikrotik', help_text='Device type this template is designed for.', max_length=30, verbose_name='Target vendor')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Key-value pairs injected into the Jinja2 context when rendering. Example: {"company": "MyWifi", "primary_color": "#4f46e5"}', verbose_name='Default template variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Hotspot Template',
                'verbose_name_plural': 'Hotspot Templates',
                'ordering': ['vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotspotTemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text="Name of the file as uploaded to the device, e.g. 'login.html'.", max_length=255, verbose_name='File name')),
                ('role', models.CharField(choices=[('login', 'Login page'), ('alogin', 'After-login redirect'), ('error', 'Error page'), ('status', 'Session status'), ('logout', 'Logout page'), ('asset', 'Static asset (CSS / JS / image)'), ('other', 'Other')], default='other', help_text='Semantic role within the portal for UI hints and validation.', max_length=20, verbose_name='File role')),
                ('content', models.TextField(verbose_name='File content (Jinja2)')),
                ('mime_type', models.CharField(default='text/html', help_text="e.g. 'text/html', 'text/css', 'application/javascript'.", max_length=100, verbose_name='MIME type')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number appears first in the UI.', verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hotspot.hotspottemplate', verbose_name='Parent template')),
            ],
            options={
                'verbose_name': 'Hotspot Template File',
                'verbose_name_plural': 'Hotspot Template Files',
                'ordering': ['template', 'order', 'filename'],
            },
        ),
        migrations.AddConstraint(
            model_name='hotspottemplatefile',
            constraint=models.UniqueConstraint(fields=('template', 'filename'), name='unique_template_filename'),
        ),
    ]
