# Generated by Django 5.0.6 on 2026-03-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Router name')),
                ('host', models.GenericIPAddressField(verbose_name='IP address or hostname')),
                ('port', models.PositiveIntegerField(default=443, verbose_name='HTTPS port')),
                ('api_username', models.CharField(max_length=100, verbose_name='API username')),
                ('api_password', models.CharField(max_length=255, verbose_name='API password')),
                ('ssl_verify', models.BooleanField(default=False, help_text='Set to True only when using a trusted CA-signed certificate.', verbose_name='Verify SSL certificate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Router',
                'verbose_name_plural': 'Routers',
                'ordering': ['name'],
            },
        ),
    ]
