# Generated by Django 5.0.6 on 2026-03-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='routeros_version',
            field=models.CharField(choices=[('v6', 'RouterOS v6'), ('v7', 'RouterOS v7')], default='v6', max_length=10, verbose_name='RouterOS version'),
        ),
    ]
