# Generated by Django 5.0.6 on 2026-03-26 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_router_routeros_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_routers', to='routers.router', verbose_name='Router')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_routers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Router',
                'verbose_name_plural': 'User Routers',
                'ordering': ['user', 'router'],
            },
        ),
        migrations.AddConstraint(
            model_name='userrouter',
            constraint=models.UniqueConstraint(fields=('user', 'router'), name='unique_user_router'),
        ),
    ]
