# Generated by Django 5.0.6 on 2026-09-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_user_router_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='api_password',
            field=models.CharField(max_length=255, unique=True, verbose_name='API password'),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_username',
            field=models.CharField(max_length=100, unique=True, verbose_name='API username'),
        ),
        migrations.AlterField(
            model_name='router',
            name='host',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP address or hostname'),
        ),
        migrations.AlterField(
            model_name='router',
            name='port',
            field=models.PositiveIntegerField(unique=True, verbose_name='HTTPS port'),
        ),
        migrations.AlterField(
            model_name='router',
            name='routeros_version',
            field=models.CharField(blank=True, choices=[('v6', 'RouterOS v6'), ('v7', 'RouterOS v7')], default=None, max_length=10, null=True, verbose_name='RouterOS version'),
        ),
    ]
