# Generated by Django 5.0.6 on 2026-03-10 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0002_router_routeros_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.TextField(verbose_name='Script content (Jinja2)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Script Template',
                'verbose_name_plural': 'Script Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouterScriptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables_used', models.JSONField(default=dict, verbose_name='Variables used')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('output_log', models.TextField(blank=True, verbose_name='Execution output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_executions', to='routers.router')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.scripttemplate')),
            ],
            options={
                'verbose_name': 'Script Execution',
                'verbose_name_plural': 'Script Executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
