# Generated by Django 5.0.6 on 2026-09-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_user_router_association'),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptDownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('variables_used', models.JSONField(blank=True, default=dict, verbose_name='Variables used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('is_consumed', models.BooleanField(default=False, verbose_name='Is consumed')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Consumed at')),
                ('include_cleanup', models.BooleanField(default=True, help_text='Appends command to remove the .rsc file from router storage after import.', verbose_name='Include self-cleanup')),
                ('filename', models.CharField(default='setup.rsc', max_length=100, verbose_name='Destination file name')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_tokens', to='scripts.routerscriptexecution', verbose_name='Script Execution')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='routers.router', verbose_name='Router')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_tokens', to='scripts.scripttemplate', verbose_name='Script Template')),
            ],
            options={
                'verbose_name': 'Script Download Token',
                'verbose_name_plural': 'Script Download Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='scripts_scr_token_a6605c_idx'), models.Index(fields=['router', '-created_at'], name='scripts_scr_router__a0bcc0_idx')],
            },
        ),
    ]
