# Generated by Django data migration

from django.db import migrations

IKEV2_TEMPLATE_NAME = "MikroTik IKEv2 VPN Client"
IKEV2_TEMPLATE_DESC = (
    "Automated MikroTik IKEv2 client setup with server certificate import, "
    "dynamic FreeRADIUS credentials, and high-priority firewall rule."
)
IKEV2_TEMPLATE_CONTENT = """# 1. Download and import VPN server certificate
/tool fetch url="{{ cert_download_url }}" mode=https dst-path="IKEv2-cert.pem";
:delay 2s;
/certificate import file-name=IKEv2-cert.pem passphrase="";
:delay 1s;

# 2. IPsec Profile
/ip ipsec profile
add name=profile-ikev2 dh-group=ecp256,modp2048 enc-algorithm=aes-256 hash-algorithm=sha256

# 3. IPsec Proposal
/ip ipsec proposal
add name=proposal-ikev2 auth-algorithms=sha256 enc-algorithms=aes-256-cbc pfs-group=none

# 4. IPsec Peer
/ip ipsec peer
add name=peer-ikev2 address={{ vpn_server_address }} profile=profile-ikev2 exchange-mode=ike2

# 5. IPsec Mode Config
/ip ipsec mode-config
add name=ikev2-request-ip responder=no

# 6. IPsec Identity (Dynamic RADIUS credentials)
/ip ipsec identity
add peer=peer-ikev2 auth-method=eap certificate="IKEv2-cert.pem_0" \\
    eap-methods=eap-mschapv2 username="{{ radius_username }}" password="{{ radius_password }}" \\
    generate-policy=port-strict mode-config=ikev2-request-ip

# 7. Firewall filter rule (placed first in the input chain)
/ip firewall filter
add chain=input src-address={{ vpn_server_internal_ip }} action=accept comment="Allow VPN Server traffic" place-before=0
"""


def seed_ikev2_template(apps, schema_editor):
    ScriptTemplate = apps.get_model("scripts", "ScriptTemplate")
    ScriptTemplate.objects.update_or_create(
        name=IKEV2_TEMPLATE_NAME,
        defaults={
            "description": IKEV2_TEMPLATE_DESC,
            "content": IKEV2_TEMPLATE_CONTENT,
        },
    )


def remove_ikev2_template(apps, schema_editor):
    ScriptTemplate = apps.get_model("scripts", "ScriptTemplate")
    ScriptTemplate.objects.filter(name=IKEV2_TEMPLATE_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0002_scriptdownloadtoken"),
    ]

    operations = [
        migrations.RunPython(seed_ikev2_template, remove_ikev2_template),
    ]
