# Generated by Django data migration

from django.db import migrations

IKEV2_TEMPLATE_NAME = "MikroTik IKEv2 VPN Client"
IKEV2_TEMPLATE_DESC = (
    "Automated MikroTik IKEv2 client setup with server certificate import, "
    "dynamic FreeRADIUS credentials, and high-priority firewall rule."
)
IKEV2_TEMPLATE_CONTENT = """# 0. Clean up previous configuration if present (idempotency)
/ip ipsec identity remove [find comment="codehook-vpn-conect"];
/ip ipsec peer remove [find name="codehook-vpn-conect"];
/ip ipsec mode-config remove [find name="codehook-vpn-conect"];
/ip ipsec proposal remove [find name="codehook-vpn-conect"];
/ip ipsec profile remove [find name="codehook-vpn-conect"];
/ip firewall filter remove [find comment="codehook-vpn-conect"];
/ip firewall filter remove [find comment="codehook-vpn-block-internet"];
/certificate remove [find name~"IKEv2-cert"];

# 1. Download and import VPN server certificate
/tool fetch url="{{ cert_download_url }}" mode=https dst-path="IKEv2-cert.pem";
:delay 2s;
/certificate import file-name=IKEv2-cert.pem passphrase="";
:delay 1s;

# 2. IPsec Profile
/ip ipsec profile
add name=codehook-vpn-conect dh-group=ecp256,modp2048 enc-algorithm=aes-256 hash-algorithm=sha256;

# 3. IPsec Proposal
/ip ipsec proposal
add name=codehook-vpn-conect auth-algorithms=sha256 enc-algorithms=aes-256-cbc pfs-group=none;

# 4. IPsec Peer
/ip ipsec peer
add name=codehook-vpn-conect address={{ vpn_server_address }} profile=codehook-vpn-conect exchange-mode=ike2;

# 5. IPsec Mode Config (disable responder DNS to prevent routing/DNS hijack)
/ip ipsec mode-config
add name=codehook-vpn-conect responder=no use-responder-dns=no;

# 6. IPsec Identity (Dynamic RADIUS credentials)
/ip ipsec identity
add peer=codehook-vpn-conect auth-method=eap certificate="IKEv2-cert.pem_0" \\
    eap-methods=eap-mschapv2 username="{{ radius_username }}" password="{{ radius_password }}" \\
    generate-policy=port-strict mode-config=codehook-vpn-conect comment="codehook-vpn-conect";

# 7. Firewall filter rules (allow management input, block internet forwarding over VPN)
/ip firewall filter
add chain=input src-address={{ vpn_server_internal_ip }} action=accept comment="codehook-vpn-conect" place-before=0;
add chain=forward ipsec-policy=out,ipsec action=drop comment="codehook-vpn-block-internet" place-before=0;
"""


def seed_ikev2_template(apps, schema_editor):
    ScriptTemplate = apps.get_model("scripts", "ScriptTemplate")
    ScriptTemplate.objects.update_or_create(
        name=IKEV2_TEMPLATE_NAME,
        defaults={
            "description": IKEV2_TEMPLATE_DESC,
            "content": IKEV2_TEMPLATE_CONTENT,
        },
    )


def remove_ikev2_template(apps, schema_editor):
    ScriptTemplate = apps.get_model("scripts", "ScriptTemplate")
    ScriptTemplate.objects.filter(name=IKEV2_TEMPLATE_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0002_scriptdownloadtoken"),
    ]

    operations = [
        migrations.RunPython(seed_ikev2_template, remove_ikev2_template),
    ]
